<?xml version="1.0" encoding="utf-8"?>

<Project>

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		
		<Version>1.1.0</Version>
		<Product>AP_Configuration</Product>
	</PropertyGroup>

</Project>

